# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ffd20f431622110bd86850a06288a993"
name = "employee-discount-app"
handle = "employee-discount-app-2"
application_url = "https://twiki-texas-germany-institution.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-for-customer-account-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_price_rules,read_products,unauthenticated_read_checkouts,unauthenticated_write_checkouts,write_customers,write_discounts,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://twiki-texas-germany-institution.trycloudflare.com/auth/callback",
  "https://twiki-texas-germany-institution.trycloudflare.com/auth/shopify/callback",
  "https://twiki-texas-germany-institution.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
