# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "073e3629717691f45681e38ff78048f0"
name = "test-employee-discount-app"
handle = "test-employee-discount-app"
application_url = "https://heavy-exterior-temporary-accomplish.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-for-customer-account-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://heavy-exterior-temporary-accomplish.trycloudflare.com/auth/callback",
  "https://heavy-exterior-temporary-accomplish.trycloudflare.com/auth/shopify/callback",
  "https://heavy-exterior-temporary-accomplish.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
